WebUI/Controllers/CartController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Models;
using System;
using RBBL;

namespace WebUI.Controllers
{
    public class CartController : Controller
    {
        private IBL _bl;
        public CartController(IBL bl)
        {
            _bl = bl;
        }
        // GET: CartController
        public ActionResult Index()
        {
            var userCheck = HttpContext.Request.Cookies["user"];
            if (userCheck == "true")
            {
                ViewData["status"] = "user";
            }
            return View(DisplayCart.cart);
        }

        public ActionResult Checkout()
        {
            if (DisplayCart.cart.Count == 0)
            {
                HttpContext.Response.Cookies.Append("checkoutMsg", "Cart is empty.");
                return RedirectToAction(nameof(Index));
            }   else
            {
                int userId = Int32.Parse(HttpContext.Request.Cookies["userId"]);
                for (int i = 0; i < DisplayCart.cart.Count; i++)
                {
                    Order newOrd = new Order();
                    _bl.AddOrder(newOrd, userId, DisplayCart.cart[i].ReturnWarehouseId(), DisplayCart.cart[i].ReturnPhotoId());
                }
                DisplayCart.cart.Clear();
                HttpContext.Response.Cookies.Append("checkoutMsg", "Checkout Successful.");
                return RedirectToAction(nameof(Index));
            } 

        }
    }
}

WebUI/Controllers/CustomerController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using RBBL;
using Models;
using WebUI.Models;

namespace WebUI.Controllers
{
    public class CustomerController : Controller
    {
        private IBL _bl;
        public CustomerController(IBL bl)
        {
            _bl = bl;
        }

        public ActionResult Confirm()
        {
            var userCheck = HttpContext.Request.Cookies["user"];
            if (userCheck == "true")
            {
                ViewData["status"] = "user";
            }
            return View();
        }
        // GET: CustomerController
        public ActionResult Index()
        {
            var adminCheck = HttpContext.Request.Cookies["admin"];
            if (adminCheck == "true")
            {
                ViewData["status"] = "admin";
            }
            List<Customer> allCustomer = _bl.GetAllCustomers();
            return View(allCustomer);
        }

        // GET: CustomerController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CustomerController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Customer customer)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _bl.AddCustomer(customer);
                    return RedirectToAction(nameof(Confirm));
                }
                return View();
            }
            catch
            {
                return View();
            }
        }

        // GET: CustomerController/Edit/5
        public ActionResult Edit(int id)
        {
            return View(_bl.GetOneCustomerById(id));
        }

        // POST: CustomerController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Customer customer)
        {
            try
            {
                _bl.UpdateCustomer(customer);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return RedirectToAction(nameof(Edit));
            }
        }

        // GET: CustomerController/Delete/5
        public ActionResult Delete(int id)
        {
            var adminCheck = HttpContext.Request.Cookies["admin"];
            if (adminCheck == "true")
            {
                ViewData["status"] = "admin";
            }
            return View(_bl.GetOneCustomerById(id));
        }

        // POST: CustomerController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, Customer customer)
        {
            try
            {
                _bl.RemoveCustomer(id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

WebUI/Controllers/OrderController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Models;
using RBBL;
using WebUI.Models;

namespace WebUI.Controllers
{
    public class OrderController : Controller
    {
        private IBL _bl;
        public OrderController(IBL bl)
        {
            _bl = bl;
        }
        // GET: OrderController
        public ActionResult Index()
        {
            List<Order> allOrd = _bl.GetAllOrders();
            List<Customer> allCustomer = _bl.GetAllCustomers();
            List<Warehouse> allWarehouse = _bl.GetAllWarehouse();
            List<Photocard> allPhotocard = _bl.GetAllPhotocard();
            List<Order> tempOrd = new List<Order>();
            int userId;
            int.TryParse(HttpContext.Request.Cookies["userId"], out userId);
            var userCheck = HttpContext.Request.Cookies["user"];
            if (userCheck == "true")
            {
                ViewData["status"] = "user";
                foreach (Order ord in allOrd)
                {
                    if (userId == ord.CustomerId)
                    {
                        tempOrd.Add(ord);
                    }
                }
                var viewmodelResult = from p in tempOrd
                                      join k in allCustomer on p.CustomerId equals k.Id
                                      join w in allWarehouse on p.WarehouseId equals w.Id
                                      join photo in allPhotocard on p.PhotocardId equals photo.Id
                                      orderby k.Id
                                      select new OrderVM { Id = p.Id, CustomerEmail = k.Email, WarehouseName = w.Name, PhotocardName = photo.SetId, DateandTime = p.DateandTime};
                return View(viewmodelResult);
                //return View(tempOrd);
            }
            else
            {
                ViewData["status"] = "admin";
                var viewmodelResult = from p in allOrd
                                      join k in allCustomer on p.CustomerId equals k.Id
                                      join w in allWarehouse on p.WarehouseId equals w.Id
                                      join photo in allPhotocard on p.PhotocardId equals photo.Id
                                      orderby p.Id
                                      select new OrderVM { Id = p.Id, CustomerEmail = k.Email, WarehouseName = w.Name, PhotocardName = photo.SetId, DateandTime = p.DateandTime };
                return View(viewmodelResult);
            }

        }
    }
}

WebUI/Controllers/PopulateController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebUI.Controllers
{
    public class PopulateController : Controller
    {
        public IActionResult Index()
        {
            var adminCheck = HttpContext.Request.Cookies["admin"];
            if (adminCheck == "true")
            {
                ViewData["status"] = "admin";
            }
            return View();
        }
    }
}

WebUI/Views/Shared/_Layout.cshtml
@{ 
    string status = (string)ViewData["status"];
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebUI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Kpop Snapshot</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        @if (status == "admin")
                        {
                            <partial name="_NavAdmin" view-data="ViewData" />
                        }
                        @if (status == "user")
                        {
                            <partial name="_NavUser" view-data="ViewData" />
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - WebUI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebUI/Views/Shared/_NavAdmin.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

<li class="nav-item">
    <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="Index">View Customers</a>
</li>
<li class="nav-item">
    <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="Index">View Orders</a>
</li>
<li class="nav-item">
    <a class="nav-link text-dark" asp-area="" asp-controller="Populate" asp-action="Index">Populate</a>
</li>

WebUI/Views/Shared/_NavUser.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

<li class="nav-item">
    <a class="nav-link text-dark" asp-area="" asp-controller="Inventory" asp-action="Browse">Browse</a>
</li>
<li class="nav-item">
    <a class="nav-link text-dark" asp-area="" asp-controller="Warehouse" asp-action="Change">Change Warehouse</a>
</li>
<li class="nav-item">
    <a class="nav-link text-dark" asp-area="" asp-controller="Cart" asp-action="Index">Cart</a>
</li>
<li class="nav-item">
    <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="Index">Order History</a>
</li>
<li class="nav-item">
    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Logout</a>
</li>